[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",".*"]

[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ¯ ç›´æ¥è¿æ¥","(å°|hk|æ¸¯|tw)",".*"]

[[custom_groups]]
name = "ğŸ® Steam"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",".*"]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ ä¸­å›½åª’ä½“"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",".*"]

[[custom_groups]]
name = "ğŸ è‹¹æœ"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "ğŸ¤– AI"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",".*"]

[[custom_groups]]
name = "ğŸŒ å…¨çƒåª’ä½“"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",".*"]

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["[]ğŸ¯ ç›´æ¥è¿æ¥","(å°|tw)",".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ¯ ç›´æ¥è¿æ¥"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸ›‘ é˜»æ­¢è¿æ¥"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",".*"]
