[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "rules/BiliBili.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯"
ruleset = "rules/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœ"
ruleset = "rules/Apple.list"

[[rulesets]]
group = "ğŸ¤– AI"
ruleset = "rules/AI.list"

[[rulesets]]
group = "ğŸŒ å…¨çƒåª’ä½“"
ruleset = "rules/GlobalMedia.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "rules/Telegram.list"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "rules/Bahamut.list"

[[rulesets]]
group = "ğŸ® Steam"
ruleset = "rules/Steam.list"

[[rulesets]]
group = "ğŸ‡¨ğŸ‡³ ä¸­å›½åª’ä½“"
ruleset = "rules/ChinaMedia.list"

[[rulesets]]
group = "ğŸ¯ ç›´æ¥è¿æ¥"
ruleset = "rules/DirectConnection.list"

[[rulesets]]
group = "ğŸ¯ ç›´æ¥è¿æ¥"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ›‘ é˜»æ­¢è¿æ¥"
ruleset = "rules/Block.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/NodePick.list"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
